# typed: false
# frozen_string_literal: true
# This file was generated by go-xbuild-go v1.0.9. DO NOT EDIT
# https://github.com/muquit/go-xbuild-go
class GithubProfilegenGo < Formula
  desc ""
  homepage "https://github.com/muquit/github-profilegen-go"
  version "1.0.5"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/muquit/github-profilegen-go/releases/download/v1.0.5/github-profilegen-go-v1.0.5-darwin-arm64.d.tar.gz"
    sha256 "0eaa7b5b5fe52178db1a81d34358518982f66e7e4aca84480c56404235cbdf70"
  elsif OS.mac? && Hardware::CPU.intel?
    url "https://github.com/muquit/github-profilegen-go/releases/download/v1.0.5/github-profilegen-go-v1.0.5-darwin-amd64.d.tar.gz"
    sha256 "e3bbbf579dbf9d2aae436e1c7fd780854a00d6183544e898d8ce569719d8f912"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/muquit/github-profilegen-go/releases/download/v1.0.5/github-profilegen-go-v1.0.5-linux-amd64.d.tar.gz"
    sha256 "1f08e5fce00ae9ac8c702b1f635f26dca85dac6bf7af93b2874a5bf40c8e067d"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/muquit/github-profilegen-go/releases/download/v1.0.5/github-profilegen-go-v1.0.5-linux-arm64.d.tar.gz"
    sha256 "a8d0dcbcd47575767a0df7d525c7e8200fdfe63848a5938d1f061d5edf0c856a"
  end

  def install
    if OS.mac?
      if Hardware::CPU.arm?
        bin.install "github-profilegen-go-v#{version}-darwin-arm64" => "github-profilegen-go"
      else
        bin.install "github-profilegen-go-v#{version}-darwin-amd64" => "github-profilegen-go"
      end
    elsif OS.linux?
      if Hardware::CPU.arm?
        bin.install "github-profilegen-go-v#{version}-linux-arm64" => "github-profilegen-go"
      else
        bin.install "github-profilegen-go-v#{version}-linux-amd64" => "github-profilegen-go"
      end
    end
  end
end
