# typed: false
# frozen_string_literal: true
# This file was generated by go-xbuild-go v1.0.9. DO NOT EDIT
# https://github.com/muquit/go-xbuild-go
class GithubProfilegenGo < Formula
  desc ""
  homepage "https://github.com/muquit/github-profilegen-go"
  version "1.0.5"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/muquit/github-profilegen-go/releases/download/v1.0.5/github-profilegen-go-v1.0.5-darwin-arm64.d.tar.gz"
    sha256 "31b79901f504ebd80f9a0a879b38306a2f1ac5eec24a7a8acb4a17febeec35ab"
  elsif OS.mac? && Hardware::CPU.intel?
    url "https://github.com/muquit/github-profilegen-go/releases/download/v1.0.5/github-profilegen-go-v1.0.5-darwin-amd64.d.tar.gz"
    sha256 "1ec97798894b948fc14b906768453438f5b187f694db2714a2de1ce20a15ec4c"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/muquit/github-profilegen-go/releases/download/v1.0.5/github-profilegen-go-v1.0.5-linux-amd64.d.tar.gz"
    sha256 "08f8e01eef367d98da970a2237227ee119e5ce9888237ba5b99cb0a89b68cb92"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/muquit/github-profilegen-go/releases/download/v1.0.5/github-profilegen-go-v1.0.5-linux-arm64.d.tar.gz"
    sha256 "03bfdaa26966375c8e95c8ef74872ed4a35084e91a1f679352b3351f8fede786"
  end

  def install
    if OS.mac?
      if Hardware::CPU.arm?
        bin.install "github-profilegen-go-v#{version}-darwin-arm64" => "github-profilegen-go"
      else
        bin.install "github-profilegen-go-v#{version}-darwin-amd64" => "github-profilegen-go"
      end
    elsif OS.linux?
      if Hardware::CPU.arm?
        bin.install "github-profilegen-go-v#{version}-linux-arm64" => "github-profilegen-go"
      else
        bin.install "github-profilegen-go-v#{version}-linux-amd64" => "github-profilegen-go"
      end
    end
  end
end
