# typed: false
# frozen_string_literal: true
# This file was generated by go-xbuild-go v1.0.9. DO NOT EDIT
# https://github.com/muquit/go-xbuild-go
class GithubProfilegenGo < Formula
  desc ""
  homepage "https://github.com/muquit/github-profilegen-go"
  version "1.0.6"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/muquit/github-profilegen-go/releases/download/v1.0.6/github-profilegen-go-v1.0.6-darwin-arm64.d.tar.gz"
    sha256 "4e543ff90f08f9012c7370a078dd9bd3448e0af6ebfb635c46ad3e3bc84ccfba"
  elsif OS.mac? && Hardware::CPU.intel?
    url "https://github.com/muquit/github-profilegen-go/releases/download/v1.0.6/github-profilegen-go-v1.0.6-darwin-amd64.d.tar.gz"
    sha256 "c09f4f1eabe6e279384376027d323c6def53d1853fab8faaafe194c9eb619922"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/muquit/github-profilegen-go/releases/download/v1.0.6/github-profilegen-go-v1.0.6-linux-amd64.d.tar.gz"
    sha256 "f14a32a87c2926e2de70bda9f8c1f40bb98dc430f61b530e98a069bf2b805469"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/muquit/github-profilegen-go/releases/download/v1.0.6/github-profilegen-go-v1.0.6-linux-arm64.d.tar.gz"
    sha256 "71ea982e0d6a1cc55d3e7e7e18c191aded95552dec524ef44dc2dd53d047026d"
  end

  def install
    if OS.mac?
      if Hardware::CPU.arm?
        bin.install "github-profilegen-go-v#{version}-darwin-arm64" => "github-profilegen-go"
      else
        bin.install "github-profilegen-go-v#{version}-darwin-amd64" => "github-profilegen-go"
      end
    elsif OS.linux?
      if Hardware::CPU.arm?
        bin.install "github-profilegen-go-v#{version}-linux-arm64" => "github-profilegen-go"
      else
        bin.install "github-profilegen-go-v#{version}-linux-amd64" => "github-profilegen-go"
      end
    end
  end
end
